#!/usr/bin/with-contenv bash

if [ "${DT_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="dpitunnel-cli --port ${DT_PORT} ${DT_USER_OPTS}"
command="$command${DT_DOH+ --ca-bundle-path=/etc/ssl/cert.pem --doh}"
command="$command${DT_DOHSERVER+ --doh-server=$DT_DOHSERVER}"

echo "*** executing => $command"
exec $command | sed -u 's/^/[DPITunnel] /'
